import type { ParcelTerrainModelAtomInstance } from "@hauska-engine/atoms";

import type { AuthorParcelSitePlanExportOptions } from "./author.js";
import type { DischargePointResolver } from "./discharge-point.js";
import type { WhoServesResolver } from "./feasibility-model.js";
import {
  composeParcelReport,
  type ParcelReportFactResolvers,
  type ComposeParcelReportOptions,
  type ReadableTerrainArtifactStore,
} from "./report-model.js";
import { emitPdfFeasibility, type PdfFeasibilityResult } from "./pdf/feasibility.js";
import { generateFeasibilityNarrative } from "./narrative-generator.js";
import {
  fetchFeasibilityNarrative,
  type NarrativeFallbackReason,
  type NarrativeSectionConfig,
} from "./narrative-section-client.js";

/**
 * FEASIBILITY STUDY export authoring (P-32 wave 1, 2026-09-04; re-cut onto
 * `composeParcelReport` 2026-09-07, R1/R3/R5).
 *
 * Composes the ONE parcel report model (geometry + every fact family +
 * drainage, `report-model.ts`), then the PDF, then persists bytes + a
 * record onto the SAME `parcel-terrain-model` atom every report type reuses
 * — never a second entity type.
 *
 * HONEST-DEGRADE CONTRACT: unlike before this re-cut, a missing site-plan
 * capability no longer fails the whole report (R2) — `composeParcelReport`
 * degrades `model.geometry` to a declared absence and every dependent
 * section follows suit; the document still renders. A missing who-serves
 * centroid or a failing who-serves read never fails the report either
 * (report-model.ts's own contract) — the utilities section ships
 * honest-absent instead.
 */
export interface AuthorParcelFeasibilityExportOptions
  extends Omit<AuthorParcelSitePlanExportOptions, "descriptor" | "artifactStore"> {
  artifactStore: ReadableTerrainArtifactStore;
  descriptor?: { address?: string; countyName?: string };
  whoServes?: WhoServesResolver;
  /** P-120 R-04. Omit to leave the three PR #404 fact families out of the
   * report as a declared out-of-scope rather than a silent omission; pass
   * `LIVE_PARCEL_REPORT_FACT_RESOLVERS` to run them. Injected rather than
   * imported so tests stay hermetic — these are live NFHL, SSURGO and HIFLD
   * reads. */
  factResolvers?: ParcelReportFactResolvers;
  /** Parcel centroid for the who-serves point read. Derived from the ring
   * when omitted and a ring is available; the read is skipped (honest
   * absence) when neither is supplied. */
  centroidOverride?: { latitude: number; longitude: number };
  /** item 19 — a flood-drainage-study flow exit the caller already has on
   * file for this parcel. Omit to skip (honest absence). */
  dischargeExitPoint?: { lat: number; lng: number };
  dischargeResolver?: DischargePointResolver;
  liveViewUrl?: string;
  narrativeOverride?: { text: string; generatedBy: string; generatedAt: string };
  /**
   * P-120 item 6. When supplied AND no `narrativeOverride` is given, the
   * narrative sections are generated by the same LLM engine that serves
   * Smart Site's live "Research this" chat, via
   * `POST /research/narrative-section`. Every failure path falls back to the
   * complete deterministic skeleton and reports why in
   * `narrativeFallbackReason` — never an error, never a half-written report.
   */
  narrativeSection?: NarrativeSectionConfig;
  /**
   * Let the narrative run live web search. OFF by default: it adds latency
   * and per-call cost to a synchronous customer path, so it is turned on at
   * the call site rather than by a deploy. Anything it finds renders on its
   * own sheet under an unverified label, never in the fact tables.
   */
  narrativeWebSearch?: boolean;
  /**
   * Generate the narrative with the LLM at all. OFF BY DEFAULT.
   *
   * Measured against grok-4.6 on 2026-09-08: 63s without web search, 95s
   * with. Property Explorer's BFF budgets 55s for the WHOLE feasibility
   * compose, so generating on every refresh would push every customer's
   * report past its own client timeout. Until narrative generation moves off
   * the synchronous path, it is requested per call and the deterministic
   * skeleton remains the default.
   */
  narrativeGenerate?: boolean;
  /** Recorded documents to cite into the narrative (P-120 item 16). */
  courthouseDocuments?: ReadonlyArray<{ citation: string; excerpt: string }>;
  /**
   * R3/R5 — the real parcel-scoped drainage study. Omit entirely to compose
   * without it (drainage ships honest-absent, zero extra IO cost — the
   * default). Pass `{ runWhenStale: true, ...RunFloodDrainageStudyOptions }`
   * to have this export read a fresh study when the persisted one is stale
   * or missing (the real production route does this; unit tests generally
   * should not, to stay off the network — see report-model.ts's module doc).
   */
  drainage?: ComposeParcelReportOptions["drainage"];
}

export interface AuthorParcelFeasibilityExportResult {
  atom: ParcelTerrainModelAtomInstance;
  pageCount: number;
  feasibilityPageCount: number;
  sitePlanAppended: boolean;
  sitePlanUnavailableReason?: string;
  sectionCount: number;
  openItemCount: number;
  /** Backfill worklist and address-first file name — see pdf/feasibility.ts. */
  absentFields: PdfFeasibilityResult["absentFields"];
  suggestedFileBaseName: string;
  /** Unverified web leads that reached the document, and what the call cost. */
  webFindings: ReadonlyArray<{ text: string; url: string; title?: string }>;
  narrativeUsage?: Record<string, unknown>;
  narrativeIsDeterministicSkeleton: boolean;
  /**
   * Why the skeleton was used. Present exactly when
   * `narrativeIsDeterministicSkeleton` is true and a generated narrative was
   * attempted or configured — the degradation is declared, not inferred from
   * a bare boolean.
   */
  narrativeFallbackReason?: NarrativeFallbackReason;
  /** Fact categories the generated narrative actually marked. */
  narrativeCitedSections?: ReadonlyArray<string>;
  /** True when `model.geometry` composed successfully. False means the
   * document still shipped (R2) but every geometry-derived section is a
   * declared absence — surfaced so a caller can distinguish "complete
   * report" from "report shipped with the geometry section down". */
  geometryComposed: boolean;
  /** True when `model.drainage` resolved to a real study (persisted or
   * freshly run) rather than honest absence. */
  drainageComposed: boolean;
}

export async function authorParcelFeasibilityExport(
  options: AuthorParcelFeasibilityExportOptions,
): Promise<AuthorParcelFeasibilityExportResult> {
  // 1) The one composition: geometry + every fact family + drainage. Never
  // fatal (R2) — a geometry failure degrades `model.geometry` and every
  // dependent section rather than throwing.
  const { model, freshDrainageStudy } = await composeParcelReport({
    ...(options.factResolvers ? { factResolvers: options.factResolvers } : {}),
    ...options,
    descriptor: options.descriptor,
  });

  // 2) Generated narrative (item 6). A caller-supplied override always wins;
  // otherwise, when configured, ask the briefing engine. Any failure leaves
  // `narrativeOverride` undefined, which falls back to
  // `model.package.narrativeSkeleton` — the pre-existing behaviour, now
  // labelled.
  let narrativeOverride = options.narrativeOverride;
  let narrativeFallbackReason: NarrativeFallbackReason | undefined;
  let narrativeCitedSections: ReadonlyArray<string> | undefined;
  let webFindings: ReadonlyArray<{ text: string; url: string; title?: string }> = [];
  let narrativeUsage: Record<string, unknown> | undefined;
  if (!narrativeOverride) {
    // IN-PROCESS FIRST (2026-09-08). The cross-repo `narrativeSection` hop
    // needed BROKERAGE_API_BASE_URL plus a SERVICE_API_KEY whose secret lives
    // in a different GCP project, and it was never configured, so every
    // report ever produced fell back to the skeleton. engine-api already runs
    // with XAI_API_KEY, so the same generation happens here with no new
    // secret. `narrativeSection` remains only as an explicit override for a
    // caller that still wants the LDT route; see the retirement note on
    // `narrative-section-client.ts`.
    const wantsGenerated =
      options.narrativeGenerate === true || options.narrativeWebSearch === true;
    const generated = wantsGenerated
      ? await generateFeasibilityNarrative(model, {
          webSearch: options.narrativeWebSearch === true,
        })
      : ({ ok: false, reason: "not-requested" } as const);
    if (generated.ok) {
      narrativeOverride = generated.narrativeOverride;
      narrativeCitedSections = generated.citedSections;
      webFindings = generated.webFindings;
      narrativeUsage = generated.usage;
    } else if (options.narrativeSection) {
      const viaService = await fetchFeasibilityNarrative({
        model,
        config: options.narrativeSection,
        courthouseDocuments: options.courthouseDocuments,
      });
      if (viaService.ok) {
        narrativeOverride = viaService.outcome.narrativeOverride;
        narrativeCitedSections = viaService.outcome.citedSections;
      } else {
        narrativeFallbackReason = viaService.reason;
      }
    } else {
      // Degraded answers name themselves. `generated.reason` says WHICH way
      // it degraded — no key, refused for want of citations, request failed —
      // rather than collapsing all of them into "not-configured".
      narrativeFallbackReason = generated.reason;
    }
  }

  // 3) Assemble the PDF from the manifest over the composed model.
  const pdf: PdfFeasibilityResult = await emitPdfFeasibility(model, {
    sitePlan: model.geometry.status === "present" ? { model: model.geometry.model } : undefined,
    sitePlanUnavailableReason: model.geometry.status === "absent" ? model.geometry.reason : undefined,
    liveViewUrl: options.liveViewUrl,
    narrativeOverride,
    webFindings,
    descriptorOverride: options.descriptor,
  });

  // 4) Persist bytes + record on the shared parcel-terrain-model atom. When
  // this composition computed a NEW drainage study (cache miss or stale),
  // persist it here too — composition itself stayed read-only.
  const ref = await options.artifactStore.put({
    parcelNodeId: options.parcelNodeId,
    format: "pdf-feasibility",
    bytes: pdf.bytes,
    contentType: "application/pdf",
  });

  const existing = (await options.storage.listPropertyAtomsByParcelNodeId(options.parcelNodeId)).find(
    (candidate): candidate is ParcelTerrainModelAtomInstance => candidate.entityType === "parcel-terrain-model",
  );
  const fetchedAt = new Date().toISOString();
  const geometryPresent = model.geometry.status === "present";
  const atom: ParcelTerrainModelAtomInstance =
    existing ?? {
      entityType: "parcel-terrain-model",
      atomDid: `pterrain_feasibility_${options.parcelNodeId.replace(/[^a-zA-Z0-9]/g, "_")}_${Date.parse(fetchedAt)}`,
      entityId: options.parcelNodeId,
      parcelNodeId: options.parcelNodeId,
      jurisdictionTenant: "property-spine",
      fetchedAt,
      extractedAt: fetchedAt,
      sourceAdapter: geometryPresent ? "usgs:3dep-dem" : "feasibility:no-terrain-resolved",
      sourceUrl: "",
      sourceCitation: geometryPresent ? "USGS 3DEP" : "no terrain data resolved for this export",
      accessPolicy: "public-paid",
      atomTier: "data",
      status: "active",
      contentHash: "",
      reasoningChain: {
        reasoningKind: "derived",
        derivationMethod: "parcel-terrain-mesh-ifc-v1",
        inputAtomRefs: [
          {
            atomDid: geometryPresent ? "composed-site-plan" : "feasibility:no-terrain-resolved",
            role: "reference-field",
            citationLabel: "usgs-3dep-dem",
          },
        ],
      },
      artifacts: {},
      coverage: {
        coverageFraction: 0,
        nodataCount: 0,
        totalCells: 0,
        resolutionMetersRequested: null,
        resolutionMetersActual: null,
        touchesNodata: false,
      },
      confidence: {
        value: geometryPresent ? 0.6 : 0.3,
        kind: "asserted",
        provenance: geometryPresent ? "USGS 3DEP DEM field; calibration pending" : "feasibility-only record; geometry composition failed on this run",
        n: 0,
        intervalWidth: 1,
      },
    };

  atom.artifacts["pdf-feasibility"] = {
    format: "pdf-feasibility",
    ref,
    byteCount: pdf.bytes.byteLength,
    pageCount: pdf.pageCount,
    sitePlanAppended: pdf.sitePlanAppended,
    ...(pdf.sitePlanUnavailableReason ? { sitePlanUnavailableReason: pdf.sitePlanUnavailableReason } : {}),
    feasibilitySectionCount: pdf.sectionCount,
    feasibilityOpenItemCount: pdf.openItemCount,
    feasibilitySupersededRunNoted: model.package.dataQuality.supersededNotes.length > 0,
    narrativeGrounded: pdf.narrativeGrounded,
    narrativeIsDeterministicSkeleton: pdf.narrativeIsDeterministicSkeleton,
    ...(narrativeFallbackReason ? { narrativeFallbackReason } : {}),
    ...(narrativeCitedSections ? { narrativeCitedSections: [...narrativeCitedSections] } : {}),
    whoServesMeasured: model.facts.utilities.status === "present",
  };
  // NOT persisted onto the artifact record: `TerrainExportArtifact` is a
  // closed type in the atom schema, and widening it is the substrate seat's
  // call. `suggestedFileBaseName` and `absentFields` therefore ride the
  // REFRESH RESPONSE only, which is a fed path (engine-api returns them
  // straight from this result). Writing a download-time read against a field
  // nothing stores would be a mechanism with a trigger and no input.

  // A freshly-computed drainage study is persisted onto the SAME shared
  // atom, in the SAME shape `authorParcelFloodDrainageReport` already writes
  // — one persisted study regardless of which report computed it.
  if (freshDrainageStudy) {
    const studyBytes = new TextEncoder().encode(JSON.stringify(freshDrainageStudy));
    const studyRef = await options.artifactStore.put({
      parcelNodeId: options.parcelNodeId,
      format: "json-flood-drainage-study",
      bytes: studyBytes,
      contentType: "application/json",
    });
    atom.artifacts["json-flood-drainage-study"] = {
      format: "json-flood-drainage-study",
      ref: studyRef,
      byteCount: studyBytes.byteLength,
      ...(freshDrainageStudy.honestEmpty ? { honestEmpty: true, honestEmptyReason: freshDrainageStudy.honestEmpty.reason } : {}),
      rainfallDepthInches: freshDrainageStudy.rainfallDepthInches,
      rainfallSource: freshDrainageStudy.rainfallSource,
      computationLibrary: freshDrainageStudy.computation.library,
      flowExitCount: freshDrainageStudy.stats.flowExitCount,
      gradientIncluded: !!freshDrainageStudy.gradient,
    };
  }

  await options.storage.writePropertyAtom(atom);

  return {
    atom,
    pageCount: pdf.pageCount,
    feasibilityPageCount: pdf.feasibilityPageCount,
    sitePlanAppended: pdf.sitePlanAppended,
    sitePlanUnavailableReason: pdf.sitePlanUnavailableReason,
    sectionCount: pdf.sectionCount,
    openItemCount: pdf.openItemCount,
    absentFields: pdf.absentFields,
    suggestedFileBaseName: pdf.suggestedFileBaseName,
    webFindings,
    ...(narrativeUsage ? { narrativeUsage } : {}),
    narrativeIsDeterministicSkeleton: pdf.narrativeIsDeterministicSkeleton,
    ...(narrativeFallbackReason ? { narrativeFallbackReason } : {}),
    ...(narrativeCitedSections ? { narrativeCitedSections } : {}),
    geometryComposed: geometryPresent,
    drainageComposed: model.drainage.status === "present",
  };
}
