import type { ParcelTerrainModelAtomInstance } from "@hauska-engine/atoms";

import type { AuthorParcelSitePlanExportOptions } from "./author.js";
import type { DischargePointResolver } from "./discharge-point.js";
import type { WhoServesResolver } from "./feasibility-model.js";
import {
  composeParcelReport,
  type ParcelReportFactResolvers,
  type ComposeParcelReportOptions,
  type ReadableTerrainArtifactStore,
} from "./report-model.js";
import { emitPdfFeasibility, type PdfFeasibilityResult } from "./pdf/feasibility.js";
import {
  fetchFeasibilityNarrative,
  type NarrativeFallbackReason,
  type NarrativeSectionConfig,
} from "./narrative-section-client.js";

/**
 * FEASIBILITY STUDY export authoring (P-32 wave 1, 2026-09-04; re-cut onto
 * `composeParcelReport` 2026-09-07, R1/R3/R5).
 *
 * Composes the ONE parcel report model (geometry + every fact family +
 * drainage, `report-model.ts`), then the PDF, then persists bytes + a
 * record onto the SAME `parcel-terrain-model` atom every report type reuses
 * — never a second entity type.
 *
 * HONEST-DEGRADE CONTRACT: unlike before this re-cut, a missing site-plan
 * capability no longer fails the whole report (R2) — `composeParcelReport`
 * degrades `model.geometry` to a declared absence and every dependent
 * section follows suit; the document still renders. A missing who-serves
 * centroid or a failing who-serves read never fails the report either
 * (report-model.ts's own contract) — the utilities section ships
 * honest-absent instead.
 */
export interface AuthorParcelFeasibilityExportOptions
  extends Omit<AuthorParcelSitePlanExportOptions, "descriptor" | "artifactStore"> {
  artifactStore: ReadableTerrainArtifactStore;
  descriptor?: { address?: string; countyName?: string };
  whoServes?: WhoServesResolver;
  /** P-120 R-04. Omit to leave the three PR #404 fact families out of the
   * report as a declared out-of-scope rather than a silent omission; pass
   * `LIVE_PARCEL_REPORT_FACT_RESOLVERS` to run them. Injected rather than
   * imported so tests stay hermetic — these are live NFHL, SSURGO and HIFLD
   * reads. */
  factResolvers?: ParcelReportFactResolvers;
  /** Parcel centroid for the who-serves point read. Derived from the ring
   * when omitted and a ring is available; the read is skipped (honest
   * absence) when neither is supplied. */
  centroidOverride?: { latitude: number; longitude: number };
  /** item 19 — a flood-drainage-study flow exit the caller already has on
   * file for this parcel. Omit to skip (honest absence). */
  dischargeExitPoint?: { lat: number; lng: number };
  dischargeResolver?: DischargePointResolver;
  liveViewUrl?: string;
  narrativeOverride?: { text: string; generatedBy: string; generatedAt: string };
  /**
   * P-120 item 6. When supplied AND no `narrativeOverride` is given, the
   * narrative sections are generated by the same LLM engine that serves
   * Smart Site's live "Research this" chat, via
   * `POST /research/narrative-section`. Every failure path falls back to the
   * complete deterministic skeleton and reports why in
   * `narrativeFallbackReason` — never an error, never a half-written report.
   */
  narrativeSection?: NarrativeSectionConfig;
  /** Recorded documents to cite into the narrative (P-120 item 16). */
  courthouseDocuments?: ReadonlyArray<{ citation: string; excerpt: string }>;
  /**
   * R3/R5 — the real parcel-scoped drainage study. Omit entirely to compose
   * without it (drainage ships honest-absent, zero extra IO cost — the
   * default). Pass `{ runWhenStale: true, ...RunFloodDrainageStudyOptions }`
   * to have this export read a fresh study when the persisted one is stale
   * or missing (the real production route does this; unit tests generally
   * should not, to stay off the network — see report-model.ts's module doc).
   */
  drainage?: ComposeParcelReportOptions["drainage"];
}

export interface AuthorParcelFeasibilityExportResult {
  atom: ParcelTerrainModelAtomInstance;
  pageCount: number;
  feasibilityPageCount: number;
  sitePlanAppended: boolean;
  sitePlanUnavailableReason?: string;
  sectionCount: number;
  openItemCount: number;
  narrativeIsDeterministicSkeleton: boolean;
  /**
   * Why the skeleton was used. Present exactly when
   * `narrativeIsDeterministicSkeleton` is true and a generated narrative was
   * attempted or configured — the degradation is declared, not inferred from
   * a bare boolean.
   */
  narrativeFallbackReason?: NarrativeFallbackReason;
  /** Fact categories the generated narrative actually marked. */
  narrativeCitedSections?: ReadonlyArray<string>;
  /** True when `model.geometry` composed successfully. False means the
   * document still shipped (R2) but every geometry-derived section is a
   * declared absence — surfaced so a caller can distinguish "complete
   * report" from "report shipped with the geometry section down". */
  geometryComposed: boolean;
  /** True when `model.drainage` resolved to a real study (persisted or
   * freshly run) rather than honest absence. */
  drainageComposed: boolean;
}

export async function authorParcelFeasibilityExport(
  options: AuthorParcelFeasibilityExportOptions,
): Promise<AuthorParcelFeasibilityExportResult> {
  // 1) The one composition: geometry + every fact family + drainage. Never
  // fatal (R2) — a geometry failure degrades `model.geometry` and every
  // dependent section rather than throwing.
  const { model, freshDrainageStudy } = await composeParcelReport({
    ...(options.factResolvers ? { factResolvers: options.factResolvers } : {}),
    ...options,
    descriptor: options.descriptor,
  });

  // 2) Generated narrative (item 6). A caller-supplied override always wins;
  // otherwise, when configured, ask the briefing engine. Any failure leaves
  // `narrativeOverride` undefined, which falls back to
  // `model.package.narrativeSkeleton` — the pre-existing behaviour, now
  // labelled.
  let narrativeOverride = options.narrativeOverride;
  let narrativeFallbackReason: NarrativeFallbackReason | undefined;
  let narrativeCitedSections: ReadonlyArray<string> | undefined;
  if (!narrativeOverride) {
    if (options.narrativeSection) {
      const generated = await fetchFeasibilityNarrative({
        model,
        config: options.narrativeSection,
        courthouseDocuments: options.courthouseDocuments,
      });
      if (generated.ok) {
        narrativeOverride = generated.outcome.narrativeOverride;
        narrativeCitedSections = generated.outcome.citedSections;
      } else {
        narrativeFallbackReason = generated.reason;
      }
    } else {
      // The absent-config path must ALSO name itself — a degraded answer
      // presented as complete is the defect; labelled is honest.
      narrativeFallbackReason = "not-configured";
    }
  }

  // 3) Assemble the PDF from the manifest over the composed model.
  const pdf: PdfFeasibilityResult = await emitPdfFeasibility(model, {
    sitePlan: model.geometry.status === "present" ? { model: model.geometry.model } : undefined,
    sitePlanUnavailableReason: model.geometry.status === "absent" ? model.geometry.reason : undefined,
    liveViewUrl: options.liveViewUrl,
    narrativeOverride,
    descriptorOverride: options.descriptor,
  });

  // 4) Persist bytes + record on the shared parcel-terrain-model atom. When
  // this composition computed a NEW drainage study (cache miss or stale),
  // persist it here too — composition itself stayed read-only.
  const ref = await options.artifactStore.put({
    parcelNodeId: options.parcelNodeId,
    format: "pdf-feasibility",
    bytes: pdf.bytes,
    contentType: "application/pdf",
  });

  const existing = (await options.storage.listPropertyAtomsByParcelNodeId(options.parcelNodeId)).find(
    (candidate): candidate is ParcelTerrainModelAtomInstance => candidate.entityType === "parcel-terrain-model",
  );
  const fetchedAt = new Date().toISOString();
  const geometryPresent = model.geometry.status === "present";
  const atom: ParcelTerrainModelAtomInstance =
    existing ?? {
      entityType: "parcel-terrain-model",
      atomDid: `pterrain_feasibility_${options.parcelNodeId.replace(/[^a-zA-Z0-9]/g, "_")}_${Date.parse(fetchedAt)}`,
      entityId: options.parcelNodeId,
      parcelNodeId: options.parcelNodeId,
      jurisdictionTenant: "property-spine",
      fetchedAt,
      extractedAt: fetchedAt,
      sourceAdapter: geometryPresent ? "usgs:3dep-dem" : "feasibility:no-terrain-resolved",
      sourceUrl: "",
      sourceCitation: geometryPresent ? "USGS 3DEP" : "no terrain data resolved for this export",
      accessPolicy: "public-paid",
      atomTier: "data",
      status: "active",
      contentHash: "",
      reasoningChain: {
        reasoningKind: "derived",
        derivationMethod: "parcel-terrain-mesh-ifc-v1",
        inputAtomRefs: [
          {
            atomDid: geometryPresent ? "composed-site-plan" : "feasibility:no-terrain-resolved",
            role: "reference-field",
            citationLabel: "usgs-3dep-dem",
          },
        ],
      },
      artifacts: {},
      coverage: {
        coverageFraction: 0,
        nodataCount: 0,
        totalCells: 0,
        resolutionMetersRequested: null,
        resolutionMetersActual: null,
        touchesNodata: false,
      },
      confidence: {
        value: geometryPresent ? 0.6 : 0.3,
        kind: "asserted",
        provenance: geometryPresent ? "USGS 3DEP DEM field; calibration pending" : "feasibility-only record; geometry composition failed on this run",
        n: 0,
        intervalWidth: 1,
      },
    };

  atom.artifacts["pdf-feasibility"] = {
    format: "pdf-feasibility",
    ref,
    byteCount: pdf.bytes.byteLength,
    pageCount: pdf.pageCount,
    sitePlanAppended: pdf.sitePlanAppended,
    ...(pdf.sitePlanUnavailableReason ? { sitePlanUnavailableReason: pdf.sitePlanUnavailableReason } : {}),
    feasibilitySectionCount: pdf.sectionCount,
    feasibilityOpenItemCount: pdf.openItemCount,
    feasibilitySupersededRunNoted: model.package.dataQuality.supersededNotes.length > 0,
    narrativeGrounded: pdf.narrativeGrounded,
    narrativeIsDeterministicSkeleton: pdf.narrativeIsDeterministicSkeleton,
    ...(narrativeFallbackReason ? { narrativeFallbackReason } : {}),
    ...(narrativeCitedSections ? { narrativeCitedSections: [...narrativeCitedSections] } : {}),
    whoServesMeasured: model.facts.utilities.status === "present",
  };

  // A freshly-computed drainage study is persisted onto the SAME shared
  // atom, in the SAME shape `authorParcelFloodDrainageReport` already writes
  // — one persisted study regardless of which report computed it.
  if (freshDrainageStudy) {
    const studyBytes = new TextEncoder().encode(JSON.stringify(freshDrainageStudy));
    const studyRef = await options.artifactStore.put({
      parcelNodeId: options.parcelNodeId,
      format: "json-flood-drainage-study",
      bytes: studyBytes,
      contentType: "application/json",
    });
    atom.artifacts["json-flood-drainage-study"] = {
      format: "json-flood-drainage-study",
      ref: studyRef,
      byteCount: studyBytes.byteLength,
      ...(freshDrainageStudy.honestEmpty ? { honestEmpty: true, honestEmptyReason: freshDrainageStudy.honestEmpty.reason } : {}),
      rainfallDepthInches: freshDrainageStudy.rainfallDepthInches,
      rainfallSource: freshDrainageStudy.rainfallSource,
      computationLibrary: freshDrainageStudy.computation.library,
      flowExitCount: freshDrainageStudy.stats.flowExitCount,
      gradientIncluded: !!freshDrainageStudy.gradient,
    };
  }

  await options.storage.writePropertyAtom(atom);

  return {
    atom,
    pageCount: pdf.pageCount,
    feasibilityPageCount: pdf.feasibilityPageCount,
    sitePlanAppended: pdf.sitePlanAppended,
    sitePlanUnavailableReason: pdf.sitePlanUnavailableReason,
    sectionCount: pdf.sectionCount,
    openItemCount: pdf.openItemCount,
    narrativeIsDeterministicSkeleton: pdf.narrativeIsDeterministicSkeleton,
    ...(narrativeFallbackReason ? { narrativeFallbackReason } : {}),
    ...(narrativeCitedSections ? { narrativeCitedSections } : {}),
    geometryComposed: geometryPresent,
    drainageComposed: model.drainage.status === "present",
  };
}
